# ML Nb. 9. K-Nearest Neighbor(K-NN) Classification

### Compiled by Amit Purswani
LinkedIn: https://www.linkedin.com/in/amit-purswani-2a073777/

<b>GitHub Repositories</b>
1. Data Analysis:
https://github.com/kranemetal/Data-Analysis-Projects

2. Machine Learning:
https://github.com/kranemetal/MachineLearning

### K-NN Notes
#### Steps
1. Choose the number K of neighbors(5 is commonly accepted), to be counted for a given datapoint.
2. Take the K nearest neighbors of the new data point, according to the Euclidean(or any other) distance.
3. Among these K neighbors, count the number of data points in eacg category.
4. Assign the new data point to the category where you counted the most neighbors.
5. Model is ready.

### Importing libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

### Import dataset

In [2]:
df = pd.read_csv('C:\\Users\krane\Desktop\datasets\Social_Network_Ads.csv')

### Basic checks on dataset

In [3]:
df.shape

(400, 3)

In [4]:
df.head()

   Age  EstimatedSalary  Purchased
0   19            19000          0
1   35            20000          0
2   26            43000          0
3   27            57000          0
4   19            76000          0

In [5]:
df.isnull().sum()

Age                0
EstimatedSalary    0
Purchased          0
dtype: int64

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Age              400 non-null    int64
 1   EstimatedSalary  400 non-null    int64
 2   Purchased        400 non-null    int64
dtypes: int64(3)
memory usage: 9.5 KB

In [7]:
df.describe()

              Age  EstimatedSalary   Purchased
count  400.000000       400.000000  400.000000
mean    37.655000     69742.500000    0.357500
std     10.482877     34096.960282    0.479864
min     18.000000     15000.000000    0.000000
25%     29.750000     43000.000000    0.000000
50%     37.000000     70000.000000    0.000000
75%     46.000000     88000.000000    1.000000
max     60.000000    150000.000000    1.000000

### Splitting independent variable X and dependent variable Y

In [8]:
x = df.iloc[:,:-1].values
y = df.iloc[:,-1].values

### Splitting the train and test datasets

In [9]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size= 0.3, random_state=0)

### Feature Scaling

In [10]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [11]:
print(x_train)

[[-1.1631724  -1.5849703 ]
 [ 2.17018137  0.93098672]
 [ 0.0133054   1.22017719]
 [ 0.20938504  1.07558195]
 [ 0.40546467 -0.48604654]
 [-0.28081405 -0.31253226]
 [ 0.99370357 -0.8330751 ]
 [ 0.99370357  1.8563962 ]
 [ 0.0133054   1.24909623]
 [-0.86905295  2.26126285]
 [-1.1631724  -1.5849703 ]
 [ 2.17018137 -0.80415605]
 [-1.35925203 -1.46929411]
 [ 0.40546467  2.2901819 ]
 [ 0.79762394  0.75747245]
 [-0.96709276 -0.31253226]
 [ 0.11134522  0.75747245]
 [-0.96709276  0.55503912]
 [ 0.30742485  0.06341534]
 [ 0.69958412 -1.26686079]
 [-0.47689368 -0.0233418 ]
 [-1.7514113   0.3526058 ]
 [-0.67297331  0.12125343]
 [ 0.40546467  0.29476771]
 [-0.28081405  0.06341534]
 [-0.47689368  2.2901819 ]
 [ 0.20938504  0.03449629]
 [ 1.28782302  2.20342476]
 [ 0.79762394  0.26584866]
 [-0.28081405  0.15017248]
 [ 0.0133054  -0.54388463]
 [-0.18277423  0.15017248]
 [-0.08473441  0.23692961]
 [ 0.0133054  -0.25469417]
 [ 2.17018137  1.104501  ]
 [-1.7514113   0.3526058 ]
 [ 1.87606192  0.12125343]
 [ 0.40546467 -0.13901799]
 [-1.1631724   0.29476771]
 [ 0.79762394  1.36477242]
 [-0.28081405 -0.25469417]
 [-1.65337148 -0.05226085]
 [-0.96709276 -0.74631796]
 [ 0.30742485  0.49720103]
 [-0.08473441 -1.06442747]
 [-1.06513258  0.58395817]
 [ 0.11134522 -0.80415605]
 [-0.96709276  1.53828669]
 [-0.67297331  1.39369146]
 [-1.26121221  0.49720103]
 [-0.28081405  0.03449629]
 [-0.08473441  0.00557724]
 [-0.28081405 -0.89091319]
 [ 0.89566375 -1.35361793]
 [-0.28081405  2.2323438 ]
 [ 0.99370357  1.97207239]
 [-1.1631724   0.46828198]
 [-1.26121221  0.26584866]
 [ 1.38586284  1.97207239]
 [ 1.28782302 -1.35361793]
 [-0.28081405 -0.28361322]
 [-0.47689368  1.24909623]
 [-0.77101313  1.07558195]
 [ 0.99370357 -1.06442747]
 [ 0.30742485  0.29476771]
 [ 0.99370357  0.75747245]
 [-0.67297331 -1.49821316]
 [-0.67297331  0.03449629]
 [ 0.50350449  1.71180097]
 [ 2.07214155  0.17909152]
 [-1.94749093 -0.74631796]
 [-0.18277423  1.39369146]
 [ 0.40546467  0.58395817]
 [ 0.89566375 -1.1511846 ]
 [-1.1631724  -0.775237  ]
 [ 0.20938504  0.23692961]
 [ 0.79762394 -0.31253226]
 [ 2.07214155 -0.80415605]
 [ 0.79762394  0.12125343]
 [-0.28081405  0.61287722]
 [-0.96709276 -0.31253226]
 [ 0.20938504 -0.37037036]
 [ 2.07214155  2.11666762]
 [ 1.87606192 -1.26686079]
 [ 1.38586284 -0.91983223]
 [ 0.89566375  1.24909623]
 [ 1.48390265  2.11666762]
 [-0.28081405 -1.23794174]
 [ 1.97410174  0.90206768]
 [ 0.69958412 -0.71739891]
 [-1.45729185  0.3526058 ]
 [ 0.79762394 -1.35361793]
 [ 0.40546467 -0.13901799]
 [-0.96709276  0.41044389]
 [ 0.0133054  -0.31253226]
 [-1.1631724   0.41044389]
 [-0.86905295 -1.2090227 ]
 [-0.08473441  0.03449629]
 [-1.55533166 -0.42820845]
 [ 0.99370357 -1.00658937]
 [ 1.09174339 -1.2090227 ]
 [ 0.0133054  -0.13901799]
 [-1.06513258 -1.52713221]
 [ 0.79762394 -1.2090227 ]
 [ 0.99370357  2.05882953]
 [-1.1631724  -1.52713221]
 [-0.28081405  0.78639149]
 [ 0.11134522 -0.31253226]
 [-1.35925203 -1.23794174]
 [-0.5749335  -1.49821316]
 [ 0.79762394  0.52612008]
 [-0.28081405 -0.34145131]
 [ 1.7780221  -0.28361322]
 [ 0.89566375 -1.03550842]
 [ 0.20938504  0.06341534]
 [-0.5749335   0.87314863]
 [-1.84945111 -1.41145602]
 [-1.26121221  0.58395817]
 [-0.28081405  0.52612008]
 [-0.96709276 -1.09334651]
 [ 1.1897832  -1.44037507]
 [ 0.20938504 -0.31253226]
 [ 1.1897832  -0.74631796]
 [-0.28081405  0.06341534]
 [ 0.20938504  2.08774857]
 [ 0.79762394 -1.09334651]
 [ 0.11134522  0.03449629]
 [-1.7514113   0.12125343]
 [-0.86905295  0.15017248]
 [-0.67297331  0.17909152]
 [ 0.89566375 -1.29577984]
 [ 0.20938504 -0.25469417]
 [-0.37885386  1.22017719]
 [ 0.0133054   0.29476771]
 [ 0.40546467  0.15017248]
 [ 0.89566375 -0.65956082]
 [ 0.11134522  0.15017248]
 [-1.84945111 -1.29577984]
 [-0.08473441  0.29476771]
 [-0.18277423 -0.28361322]
 [ 0.30742485 -0.51496559]
 [-0.18277423  1.59612479]
 [ 0.99370357 -1.18010365]
 [-0.18277423  1.62504383]
 [ 1.28782302  1.8563962 ]
 [-1.06513258 -0.37037036]
 [ 0.0133054   0.03449629]
 [ 0.11134522 -0.25469417]
 [-1.55533166 -1.23794174]
 [-0.47689368 -0.28361322]
 [ 0.99370357  0.12125343]
 [ 1.97410174 -1.35361793]
 [ 1.48390265  0.06341534]
 [-0.5749335   1.36477242]
 [ 1.58194247  0.00557724]
 [-0.77101313  0.29476771]
 [ 1.97410174  0.7285534 ]
 [-1.1631724  -0.51496559]
 [ 0.69958412  0.26584866]
 [-1.35925203 -0.42820845]
 [ 0.20938504  0.15017248]
 [-0.47689368 -1.2090227 ]
 [ 0.6015443   2.00099143]
 [-1.55533166 -1.49821316]
 [-0.47689368 -0.54388463]
 [ 0.50350449  1.82747716]
 [-1.35925203 -1.09334651]
 [ 0.79762394 -1.38253697]
 [-0.28081405 -0.42820845]
 [ 1.58194247  0.98882482]
 [ 0.99370357  1.42261051]
 [-0.28081405 -0.48604654]
 [-0.08473441  2.14558666]
 [-1.45729185 -0.11009894]
 [-0.08473441  1.94315334]
 [-0.67297331 -0.34145131]
 [-0.47689368 -0.8330751 ]
 [ 0.69958412 -1.38253697]
 [-0.77101313 -1.5849703 ]
 [-1.84945111 -1.46929411]
 [ 1.09174339  0.12125343]
 [ 0.11134522  1.50936765]
 [-0.28081405  0.09233438]
 [ 0.11134522  0.03449629]
 [-1.35925203 -1.35361793]
 [ 0.30742485  0.06341534]
 [-0.86905295  0.38152485]
 [ 1.58194247 -1.26686079]
 [-0.28081405 -0.74631796]
 [-0.08473441  0.15017248]
 [-0.86905295 -0.65956082]
 [-0.67297331 -0.05226085]
 [ 0.40546467 -0.45712749]
 [-0.77101313  1.88531525]
 [ 1.38586284  1.27801528]
 [ 1.1897832  -0.97767033]
 [ 1.7780221   1.82747716]
 [-0.86905295 -0.25469417]
 [-0.77101313  0.55503912]
 [-1.1631724  -1.55605125]
 [-0.47689368 -1.12226556]
 [ 0.30742485  0.06341534]
 [-0.18277423 -1.06442747]
 [ 1.67998229  1.59612479]
 [ 0.99370357  1.76963906]
 [ 0.30742485  0.03449629]
 [-0.77101313 -0.22577513]
 [-0.08473441  0.06341534]
 [ 0.30742485 -0.19685608]
 [ 1.97410174 -0.65956082]
 [-0.77101313  1.33585337]
 [-1.7514113  -0.60172273]
 [-0.08473441  0.12125343]
 [ 0.30742485 -0.31253226]
 [ 1.09174339  0.55503912]
 [-0.96709276  0.26584866]
 [ 1.48390265  0.3526058 ]
 [ 0.20938504 -0.37037036]
 [ 2.17018137 -1.03550842]
 [-0.28081405  1.104501  ]
 [-1.65337148  0.06341534]
 [ 0.0133054   0.03449629]
 [ 0.11134522  1.04666291]
 [-0.08473441 -0.37037036]
 [-1.1631724   0.06341534]
 [-0.28081405 -1.35361793]
 [ 1.58194247  1.104501  ]
 [-0.77101313 -1.52713221]
 [ 0.11134522  1.8563962 ]
 [-0.86905295 -0.775237  ]
 [-0.47689368 -0.775237  ]
 [-0.28081405 -0.91983223]
 [ 0.30742485 -0.71739891]
 [ 0.30742485  0.06341534]
 [ 0.11134522  1.8563962 ]
 [-1.06513258  1.94315334]
 [-1.65337148 -1.55605125]
 [-1.1631724  -1.09334651]
 [-0.67297331 -0.11009894]
 [ 0.11134522  0.09233438]
 [ 0.30742485  0.26584866]
 [ 0.89566375 -0.57280368]
 [ 0.30742485 -1.1511846 ]
 [-0.08473441  0.67071531]
 [ 2.17018137 -0.68847986]
 [-1.26121221 -1.38253697]
 [-0.96709276 -0.94875128]
 [ 0.0133054  -0.42820845]
 [-0.18277423 -0.45712749]
 [-1.7514113  -0.97767033]
 [ 1.7780221   0.98882482]
 [ 0.20938504 -0.37037036]
 [ 0.40546467  1.104501  ]
 [-1.7514113  -1.35361793]
 [ 0.20938504 -0.13901799]
 [ 0.89566375 -1.44037507]
 [-1.94749093  0.46828198]
 [-0.28081405  0.26584866]
 [ 1.87606192 -1.06442747]
 [-0.37885386  0.06341534]
 [ 1.09174339 -0.89091319]
 [-1.06513258 -1.12226556]
 [-1.84945111  0.00557724]
 [ 0.11134522  0.26584866]
 [-1.1631724   0.32368675]
 [-1.26121221  0.29476771]
 [-0.96709276  0.43936294]
 [ 1.67998229 -0.89091319]
 [ 1.1897832   0.52612008]
 [ 1.09174339  0.52612008]
 [ 1.38586284  2.31910094]
 [-0.28081405 -0.13901799]
 [ 0.40546467 -0.45712749]
 [-0.37885386 -0.775237  ]
 [-0.08473441 -0.51496559]
 [ 0.99370357 -1.1511846 ]
 [-0.86905295 -0.775237  ]
 [-0.18277423 -0.51496559]
 [-1.06513258 -0.45712749]
 [-1.1631724   1.39369146]]

In [12]:
print(x_test)

[[-0.77101313  0.49720103]
 [ 0.0133054  -0.57280368]
 [-0.28081405  0.15017248]
 [-0.77101313  0.26584866]
 [-0.28081405 -0.57280368]
 [-1.06513258 -1.44037507]
 [-0.67297331 -1.5849703 ]
 [-0.18277423  2.14558666]
 [-1.94749093 -0.05226085]
 [ 0.89566375 -0.775237  ]
 [-0.77101313 -0.60172273]
 [-0.96709276 -0.42820845]
 [-0.08473441 -0.42820845]
 [ 0.11134522  0.20801057]
 [-1.7514113   0.46828198]
 [-0.5749335   1.36477242]
 [-0.08473441  0.20801057]
 [-1.84945111  0.43936294]
 [ 1.67998229  1.74072002]
 [-0.28081405 -1.38253697]
 [-0.28081405 -0.65956082]
 [ 0.89566375  2.14558666]
 [ 0.30742485 -0.54388463]
 [ 0.89566375  1.01774386]
 [-1.45729185 -1.2090227 ]
 [ 1.09174339  2.05882953]
 [-0.96709276  0.49720103]
 [-0.86905295  0.29476771]
 [-0.08473441 -0.22577513]
 [-0.5749335   0.46828198]
 [-1.65337148  0.52612008]
 [-0.08473441  0.26584866]
 [ 1.87606192 -0.28361322]
 [-0.08473441 -0.48604654]
 [-1.35925203 -0.34145131]
 [-1.94749093 -0.51496559]
 [-1.55533166  0.32368675]
 [-0.37885386 -0.775237  ]
 [-0.67297331 -1.03550842]
 [ 1.09174339 -0.97767033]
 [-1.06513258  0.52612008]
 [ 0.30742485 -0.51496559]
 [-1.06513258  0.41044389]
 [-0.28081405 -1.44037507]
 [ 0.50350449  1.22017719]
 [-1.06513258 -0.34145131]
 [-0.08473441  0.29476771]
 [ 1.38586284  0.58395817]
 [-1.1631724  -1.1511846 ]
 [ 1.09174339  0.46828198]
 [ 1.87606192  1.50936765]
 [-0.37885386 -1.29577984]
 [-0.28081405 -0.37037036]
 [-0.37885386  1.30693432]
 [ 2.07214155  0.52612008]
 [ 0.69958412 -1.09334651]
 [-0.86905295  0.38152485]
 [-1.1631724   0.29476771]
 [ 1.09174339 -1.2090227 ]
 [-1.45729185 -1.44037507]
 [-0.5749335  -1.49821316]
 [ 2.17018137 -0.80415605]
 [-1.84945111  0.17909152]
 [-0.18277423  0.84422958]
 [-1.84945111 -1.26686079]
 [ 2.17018137  0.38152485]
 [-1.35925203  0.55503912]
 [-1.06513258 -0.34145131]
 [ 0.20938504 -0.65956082]
 [ 0.40546467  0.00557724]
 [-0.5749335   2.31910094]
 [-0.28081405  0.20801057]
 [-1.55533166 -0.19685608]
 [ 0.69958412 -1.38253697]
 [-1.06513258  0.55503912]
 [-1.94749093  0.3526058 ]
 [ 0.40546467  0.26584866]
 [ 0.20938504 -0.28361322]
 [ 1.48390265 -1.03550842]
 [ 0.89566375  1.07558195]
 [ 1.97410174  2.14558666]
 [ 2.07214155  0.38152485]
 [-1.35925203 -0.42820845]
 [-1.1631724  -1.00658937]
 [ 1.97410174 -0.91983223]
 [ 0.40546467  0.29476771]
 [ 0.20938504  0.15017248]
 [ 2.07214155  1.74072002]
 [ 0.79762394 -0.8330751 ]
 [ 0.30742485 -0.28361322]
 [ 0.40546467 -0.16793703]
 [-0.08473441  2.20342476]
 [-1.45729185 -0.63064177]
 [-1.26121221 -1.06442747]
 [-1.35925203  0.41044389]
 [-1.06513258  0.75747245]
 [-1.45729185 -0.19685608]
 [ 0.99370357 -1.06442747]
 [ 0.99370357  0.58395817]
 [ 0.40546467  0.98882482]
 [ 0.6015443  -0.89091319]
 [-0.5749335   1.45152956]
 [ 0.0133054  -0.57280368]
 [-0.5749335   1.88531525]
 [ 1.38586284 -1.41145602]
 [ 1.48390265  0.98882482]
 [ 0.11134522 -0.80415605]
 [ 0.0133054  -0.25469417]
 [-0.18277423 -0.57280368]
 [-0.18277423 -0.19685608]
 [-0.28081405 -1.29577984]
 [-0.28081405 -0.57280368]
 [ 0.40546467  0.09233438]
 [ 0.89566375 -0.60172273]
 [ 2.07214155 -1.18010365]
 [ 1.09174339 -0.13901799]
 [ 0.69958412  1.76963906]
 [-0.67297331  0.55503912]
 [ 0.79762394  0.3526058 ]
 [ 0.89566375 -0.54388463]]

### Train K-NN model on train set

In [14]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=5, metric = 'minkowski', p=2) 
classifier.fit(x_train, y_train) 
# n_neighbors is k, minkowski & p=2 means Euclidean distance, minkowski & p=1 means Manhattan distance,
# Manhattan distance is city-block distance or taxi-cab distance
# Euclidean distance is geometric distance(straight line) in Euclidean space

KNeighborsClassifier()

### Predicting a new result
For a customer aged 35 years and earning USD 82k

In [18]:
print(classifier.predict(sc.transform([[35,82000]])))

[0]

### Predicting the test results

In [22]:
y_pred = classifier.predict(x_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [0 0]
 [0 0]
 [1 1]
 [0 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 0]
 [1 1]]

### Checking the confusion matrix and accuracy score

In [27]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred) #confusion matrix(actual, predicted)
print(cm)
accuracy_score(y_test, y_pred) #accuracy score (actual, predicted)

[[73  6]
 [ 4 37]]

0.9166666666666666

<b>Note:</b> Here correct predictions from two classes combined is 73+37=110 and incorrect predictions from two classes combined is 6+4=10.<br>
    Hence, the accuracy is 110/(110+10=120) = 91%.

### <center>The End